services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongo
    command: yarn start:dev
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DATABASE}
                  
volumes:
  mongo: